name: cnlp_env
channels:
  - fastai
  - conda-forge
  - defaults
dependencies:
  - conda=4.9.2
  - dask=2.26.0
  - fastai=1.0.61
  - flask=1.1.2
  - gcsfs=0.7.1
  - h5py=2.10.0
  - hdf5=1.10.6
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - markdown=3.2.2
  - markupsafe=1.1.1
  - matplotlib=3.3.1=1
  - networkx=2.5
  - ninja=1.10.1
  - nltk=3.4.4
  - nodejs=14.10.1
  - nose=1.3.7
  - numpy=1.16.5
  - openpyxl=3.0.5
  - pandas=1.1.2
  - pip=20.2.3
  - psutil=5.7.2
  - pycurl=7.43.0.5
  - python=3.7.8
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - xlrd=1.2.0
  - xlsxwriter=1.3.3
  - yaml=0.2.5
  - pip:
    - datasets==1.2.1
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - libcst==0.3.17
    - multiprocess==0.70.11.1
    - notebook-executor==0.2
    - nvidia-ml-py3==7.352.0
    - opt-einsum==3.3.0
    - proto-plus==1.13.0
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - sacremoses==0.0.43
    - sentencepiece==0.1.95
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - tokenizers==0.9.4
    - torch==1.6.0+cu101
    - torchtext==0.7.0
    - torchvision==0.7.0+cu101
    - transformers==4.0.0
    - typing-inspect==0.6.0
    - xxhash==2.0.0
